apiVersion: core.example.com/v1
kind: ResourceTemplate
metadata:
  name: example-resourcetemplate
  namespace: default
spec:
  resources:
    - group: apps
      version: v1
      kind: Deployment
      name: example-deployment
