# permissions for end users to view resourcetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dynamic-controller
    app.kubernetes.io/managed-by: kustomize
  name: resourcetemplate-viewer-role
rules:
- apiGroups:
  - core.example.com
  resources:
  - resourcetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.example.com
  resources:
  - resourcetemplates/status
  verbs:
  - get
